# Generated by Django 2.1.5 on 2019-02-02 21:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Create_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('item_name', models.CharField(max_length=250)),
                ('unit_name', models.CharField(choices=[('CBM', 'CUBIC METERS'), ('CCM ', 'CUBIC CENTIMETERS '), ('CMS', 'CENTIMETERS'), ('GMS', 'GRAMMES'), ('KGS ', 'KILOGRAMMES '), ('KLR', 'KILOLITRE'), ('KME', 'KILOMETER'), ('MLT ', 'MILILITRE '), ('MTR', 'METERS'), ('OTH ', 'OTHERS '), ('QTL', 'QUINTAL'), ('SQF', 'SQUARE FEET '), ('SQM', 'SQUARE METERS'), ('TBS ', 'TABLETS '), ('QTL', 'QUINTAL')], max_length=250)),
                ('unit_quanity', models.IntegerField()),
                ('unit_quanity_type', models.CharField(choices=[('BAG', 'BAGS'), ('BOX ', 'BOX '), ('BTL', 'BOTTLES'), ('DOZ', 'DOZENS'), ('BDL ', 'BUNDLES '), ('CAN', 'CANS'), ('PAC', 'PACKETS')], max_length=250)),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('others_charges', models.TextField(max_length=300)),
                ('startdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=250)),
                ('builiding_name', models.CharField(max_length=250)),
                ('block_no', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('pincode', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(to='simple.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.Blog')),
            ],
        ),
        migrations.CreateModel(
            name='Group_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_create', to='simple.Customer_create')),
            ],
        ),
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='group_details',
            name='grouplist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouplist', to='simple.GroupList'),
        ),
    ]
