# Generated by Django 2.1.5 on 2019-02-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_details',
            name='customer_create',
        ),
        migrations.AddField(
            model_name='group_details',
            name='customer_create',
            field=models.ManyToManyField(related_name='customer_create', to='simple.Customer_create'),
        ),
    ]
