# Generated by Django 2.1.5 on 2019-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_auto_20190204_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_item',
            name='unit_name',
            field=models.CharField(choices=[('CBM', 'CUBIC METERS'), ('CCM ', 'CUBIC CENTIMETERS '), ('CMS', 'CENTIMETERS'), ('GMS', 'GRAMMES'), ('KGS ', 'KILOGRAMMES '), ('KLR', 'KILOLITRE'), ('KME', 'KILOMETER'), ('MLT ', 'MILILITRE '), ('MTR', 'METERS'), ('OTH ', 'OTHERS '), ('QTL', 'QUINTAL'), ('SQF', 'SQUARE FEET '), ('SQM', 'SQUARE METERS'), ('TBS ', 'TABLETS '), ('QTL', 'QUINTAL'), ('SCH', 'SACHET'), ('NUM', 'NUMBERS')], max_length=250),
        ),
        migrations.AlterField(
            model_name='create_item',
            name='unit_quanity_type',
            field=models.CharField(choices=[('BAG', 'BAGS'), ('BOX ', 'BOX '), ('BTL', 'BOTTLES'), ('DOZ', 'DOZENS'), ('BDL ', 'BUNDLES '), ('CAN', 'CANS'), ('PAC', 'PACKETS'), ('SHEET', 'SHEETS')], max_length=250),
        ),
    ]
